## Functions to calculate matrix inverse with caching 


## Create a object that stores a matrix and its reverse
## return methods to get and set the values

makeCacheMatrix <- function(mat = matrix()) {
  inverse <- NULL
  set <- function(x) {
    mat <<- x
    inverse <<- NULL
  }
  get <- function() mat
  setInverse <- function(inv) inverse <<- inv
  getInverse <- function() inverse
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## Get the inverse matrix of given matrix-like object x generated by makeCacheMatrix 
## Use cached value when abvailble 

cacheSolve <- function(x, ...) {
  ## Try to get cached value
  inv <- x$getInverse()
  if(!is.null(inv)) {
    message("getting cached data")
    return(m)
  }
  mat <- x$get()
  inv <- solve(mat, ...)
  ## caches for later use
  x$setmean(inv)
  inv
}
